### ISSUE TITLE
Tag picker in stream positioned absolute when scrolling

### ISSUE THREAD

**Issue by maartenkling** [ploneintranet/ploneintranet#425] opened 2015-07-08 14:22 UTC
try and add a tag to a page scroll down and this will happen

<img width="785" alt="screen shot 2015-07-08 at 16 21 01" src="https://cloud.githubusercontent.com/assets/946684/8572518/62fad8bc-258d-11e5-8262-689c81ed08e2.png">

**Comment by cornae** [comment] 2015-07-17 10:57
This is by design. When the tooltip pattern was created, it was a consideration to also close it on a scroll event, but that could lead unexpected closing of the tooltip. Letting the tooltip 'follow' the trigger element would be a great addition if it's technically feasible. Should be a ticket for @jcbrand the probably. Up to @gyst to decide if there's budget for that.

**Comment by gyst** [comment] 2015-07-17 14:29
@jcbrand your input please on how feasible it is to make the tooltip positioned relatively to the trigger instead of absolutely.

**Comment by jcbrand** [comment] 2015-07-20 12:46
@cornae I don't understand why you think that the tooltip needs to be positioned absolutely. The tooltip's `closing` option can be set to `sticky`, which means that the tooltip will only be closed if it's clicked.

So an absolute position doesn't sound necessary to me.

**Comment by gyst** [comment] 2015-07-20 14:38
@jcbrand The way I understand @cornae the absolute positioning of the tooltip is a technical constraint of the pattern used. The tooltip container injected by the pattern is appended in the body of the html page, not as a child of the trigger element. Hence, relative positioning does not appear to be possible in the current implementation. Also, the whole way the position is set in javascript assumes absolute positioning AFAICT. Would it be hard to inject the tooltip as a child of the trigger and enable relative positioning to the trigger element?

**Comment by jcbrand** [comment] 2015-07-20 16:15
@gyst The DOM element where the tooltip is inserted into can be specified with the `target` argument and by default it'll be the `<body>` tag, but it doesn't have to be.

**Comment by gyst** [comment] 2015-07-20 17:38
Assigning to @cornae to fix in proto before we implement in dev.

**Comment by cornae** [comment] 2015-08-04 11:10
Injecting in place is not an option, because it leads most of the time to styling issues, which is why absolute positioning as last child of the body tag is how it's done and is also the only right way to do it. For me the current pattern is fine. But if the fact that the tooltip doesn't scroll with the trigger, then the pattern could be extended such that the `top:` value is increased or decreased with the scroll position of the trigger element.

@jcbrand I think Guido didn't mean `position: relative` but only that it follows the position of the trigger element.

**Closed as completed** 2015-09-25 13:52 UTC
Labels: bug, wontfix, pkg-activitystream, UI
