### ISSUE TITLE
Stream comment injection removes already-existing comments (only visually)

### ISSUE THREAD

**Issue by maartenkling** [ploneintranet/ploneintranet#408] opened 2015-07-08 13:42 UTC
sometimes you will see 2 items, sometimes none, refreshing shows all commenting again

**Comment by pilz** [comment] 2015-07-12 14:22
What do I have to do to "leave comment 4 times"?

**Comment by gyst** [comment] 2015-07-13 09:22
Sounds like a dupe of #74 which shouldve been fixed in #291 but maybe is not.

**Comment by gyst** [comment] 2015-07-13 12:24
Injection error: new comment removes old comments.

**Comment by gyst** [comment] 2015-07-15 22:17
The injection needs to be fixed. @ale-rt this one is for you :-)

**Comment by gyst** [comment] 2015-07-16 07:56
I have the sources for the injection diagram documentation on my laptop so can provide an updated doc for that as soon as it's clear how it's changed.

**Closed as completed** 2015-07-16 13:48 UTC
Labels: bug, pkg-activitystream, UI, documentation
