### ISSUE TITLE
POSKeyError during demo contents creation

### ISSUE THREAD

**Issue by giacomos** [ploneintranet/ploneintranet#251] opened 2015-06-01 15:44 UTC
I faced a POSKeyError when importing the GS profile for creating demo contents. 

Step to reproduce:
- make a buildout
- create a plone site and install plone intranet suite
- import the GS step for creating demo contents.

Digging a little into the code, I found that the error happens during the creation of microblog entries, notably when the creation rate grows up and the microblog container starts to spawn threads. When it comes to flush the data and commit the transaction, that's where the POSKeyError raises.

Could it be somehow related to the performances of the system where it's deployed? 'Cause I never seen that error locally, just on our servers.

As a workaround I disable the threads generation by setting MAX_QUEUE_AGE = 0 in https://github.com/ploneintranet/ploneintranet/blob/master/src/ploneintranet/microblog/statuscontainer.py#L41

**Comment by mattss** [comment] 2015-06-01 15:58
I've never seen this myself. Did you use the 'Plone Intranet Social Suite (Demo)' GS profile, or the 'Plone Intranet Suite: Create Testing Content' profile? The former is a hangover from plonesocial and should probably be ditched.

**Comment by giacomos** [comment] 2015-06-02 01:54
I used the latter as I always do. No difference from the previous times I deployed it, as far as I could say. BTW I faced this issue even after removing the buildout completely and starting from scratch so it was deterministic. In fact as soon as I set the MAX_QUEUE_AGE to 0 everything worked smoothly. I could give more details on the server environment if needed.

**Comment by mattss** [comment] 2015-06-02 08:59
This does sound like it might be related to the system performance, but I don't understand the microblog threading stuff fully. @gyst may be able to provide further insight.

**Comment by gyst** [comment] 2015-07-20 11:44
#324 may be a duplicate of this and offers a reliable reproduction of the issue.

**Comment by gyst** [comment] 2015-07-20 11:47
Related, I've "fixed" this in setuphandlers by introducing intermediate commits between the testcontent sections. It was not just the microblog in that scenario.
https://github.com/ploneintranet/ploneintranet/commit/1fff453d0e5702c3ab3dab9e6183f9a919050b95#diff-12a1adb3d66e832dade8276e4d976640

**Comment by pilz** [comment] 2015-08-27 14:01
I have never seen this, is this still an issue? @giacomos stop me or I'll close it :)

**Comment by gyst** [comment] 2015-08-27 20:28
Can't reproduce anymore, neither with zeo on solr nor with zeo on zcatalog. Apparently the intermediate commits resolved the issue.

**Comment by gyst** [comment] 2015-08-27 20:28
Closing.

**Closed as completed by gyst** 2015-08-27 20:28 UTC
Labels: bug
