### ISSUE TITLE
Search for docs in sidebar is broken

### ISSUE THREAD

**Issue by ebrehault** [ploneintranet/ploneintranet#904] opened 2016-12-15 14:45 UTC
In a workspace, if we click on Documents in the sidebar, and then use the search, nothing happens, and in the console we can see the following response to the AJAX call:
`{"error_type": "SolrError"}`

**Comment by ale-rt** [comment] 2017-01-05 16:04
Hi @ebrehault, sorry for the delay but as described in #900 the development moved to another repo and in the current master I cannot reproduce it.

Did you get a solution for this issue? Maybe solr was not updated?
Sometimes the buildout recipe for building solr does not rebuild the schema when the indexes are modified.

**Comment by ebrehault** [comment] 2017-01-05 16:14
@ale-rt I got this bug on https://try.quaive.net so I am not able to check the solr install.
I agree it might be due to the install.

**Comment by ale-rt** [comment] 2017-01-05 16:39
As a non admin user I was not able to replicate it on try.quaive.net.
I would maybe close this.

**Comment by pysailor** [comment] 2017-01-05 16:50
I think this was fixed in quaive/ploneintranet#1022

**Closed as completed by pysailor** 2017-01-05 16:50 UTC
Labels: bug
