### ISSUE TITLE
Its 8juli and my event is on 9th and shown in old events?

### ISSUE THREAD

**Issue by maartenkling** [ploneintranet/ploneintranet#404] opened 2015-07-08 13:35 UTC
<img width="402" alt="screen shot 2015-07-08 at 15 34 25" src="https://cloud.githubusercontent.com/assets/946684/8571418/e01c4d00-2586-11e5-89a3-f3f5fbb3c41a.png">

**Comment by pilz** [comment] 2015-07-09 17:38
I can't reproduce that. What is your local timezone? Could it be something with summer time? what did you enter for the end date?

![screen shot 2015-07-09 at 19 37 28](https://cloud.githubusercontent.com/assets/138906/8602321/089bfb2c-2672-11e5-8fea-f385b67419fa.png)

**Comment by ale-rt** [comment] 2015-07-17 14:31
Cannot reproduce this, but there is a whole bunch of ticket about event dates: see #432 #561#571 #598 #599.
Apparently the categorization of the events is working fine, what is not working was the editing (now it should).

I would close this one and focus on the others.

**Comment by gyst** [comment] 2015-07-17 14:40
OK closing.

**Closed as completed by gyst** 2015-07-17 14:40 UTC
Labels: events
